import type { Agent } from "../types/content";

export const agents: Agent[] = [
  {
    slug: "yield-scanner",
    name: "Yield Scanner Agent",
    status: "Building",
    problem: "Manually checking 20+ protocols for yield anomalies takes hours.",
    whatItDoes: "Compares protocol yields against benchmarks and prepares a daily watchlist for manual review.",
    inputs: ["Protocol APIs", "Defillama data", "On-chain rates"],
    outputs: ["Daily yield digest", "Anomaly alerts", "Rate comparisons"],
    stack: ["Python", "Claude API", "Defillama API", "Telegram"],
    notes: "Keep as Building until a real repo or demo link is available.",
  },
  {
    slug: "memo-drafter",
    name: "Research Memo Drafter",
    status: "Building",
    problem: "Structuring raw thesis notes into formatted research memos is slow and repetitive.",
    whatItDoes: "Turns rough notes into a memo outline with thesis, evidence sections, risks, and source gaps.",
    inputs: ["Raw notes (markdown)", "Sector context", "Protocol docs"],
    outputs: ["Structured memo draft", "Risk checklist", "Source suggestions"],
    stack: ["Claude 3.5 Sonnet", "Structured outputs", "Next.js"],
    notes: "Drafting workflow is in progress and should not be presented as a live product yet.",
  },
  {
    slug: "protocol-monitor",
    name: "Protocol Health Monitor",
    status: "Building",
    problem: "Tracking TVL, revenue, and token emissions across a watchlist requires repeated manual checks.",
    whatItDoes: "Monitors a protocol watchlist and flags notable changes for weekly research review.",
    inputs: ["Dune queries", "Defillama", "Token Terminal"],
    outputs: ["Weekly health report", "Threshold alerts", "Trend signals"],
    stack: ["Python", "Dune API", "Claude API", "Email"],
    notes: "Needs source connectors and alert thresholds before it can be marked Live.",
  },
  {
    slug: "sentiment-agent",
    name: "Governance Sentiment Analyzer",
    status: "Planned",
    problem: "Reading 50+ DAO governance forums for signal vs. noise is not scalable.",
    whatItDoes: "Will summarize proposal arguments, sentiment, and possible vote outcomes across governance venues.",
    inputs: ["Snapshot proposals", "Forum threads", "Discord exports"],
    outputs: ["Sentiment score", "Key arguments", "Vote prediction"],
    stack: ["Claude API", "Web scraping", "Embeddings"],
    notes: "Planned research automation idea; no live workflow yet.",
  },
  {
    slug: "flow-detector",
    name: "Smart Money Flow Detector",
    status: "Planned",
    problem: "Identifying institutional on-chain positioning before price moves requires wallet-level monitoring.",
    whatItDoes: "Will cluster wallet behavior and flag position changes around tracked protocols.",
    inputs: ["Etherscan", "Nansen labels", "Dune analytics"],
    outputs: ["Flow alerts", "Wallet clusters", "Position changes"],
    stack: ["Python", "Dune API", "Nansen API", "Claude"],
    notes: "Planned until data access and alert rules are defined.",
  },
];
