import type { Agent } from "../types/content";

export const agents: Agent[] = [
  {
    slug: "research-feed-agent",
    name: "Research Feed Agent",
    status: "Building",
    problem: "Research inputs arrive across feeds, docs, dashboards, and notes.",
    whatItDoes: "Organizes incoming research material into a review queue for Yash to triage manually.",
    inputs: ["Saved links", "Protocol docs", "Dashboard notes", "Manual tags"],
    outputs: ["Review queue", "Topic clusters", "Follow-up prompts"],
    stack: ["Python", "RSS/API connectors", "LLM summarization", "Manual review"],
    notes: "Building workflow. Not a live product.",
  },
  {
    slug: "protocol-memo-agent",
    name: "Protocol Memo Agent",
    status: "Building",
    problem: "Draft memos need a consistent structure before source-backed analysis is added.",
    whatItDoes: "Turns rough notes into a memo scaffold with thesis, evidence gaps, risk checklist, and source slots.",
    inputs: ["Raw notes", "Article outline", "Source list"],
    outputs: ["Memo scaffold", "Evidence gaps", "Risk checklist"],
    stack: ["Structured outputs", "Markdown", "Manual review"],
    notes: "Building. Draft output still requires human research and editing.",
  },
  {
    slug: "dashboard-research-agent",
    name: "Dashboard Research Agent",
    status: "Planned",
    problem: "Dashboard ideas need clear research questions before queries or charts are built.",
    whatItDoes: "Will convert dashboard ideas into question lists, source requirements, and chart outlines.",
    inputs: ["Dashboard brief", "Research question", "Known sources"],
    outputs: ["Chart outline", "Source checklist", "Data gaps"],
    stack: ["Planning workflow", "Python", "Manual review"],
    notes: "Planned. No working demo yet.",
  },
  {
    slug: "claim-checker-agent",
    name: "Claim Checker Agent",
    status: "Planned",
    problem: "Draft research claims need to be separated from sourced evidence.",
    whatItDoes: "Will flag unsupported claims and route them into a manual verification queue.",
    inputs: ["Draft memo", "Source notes", "Claim list"],
    outputs: ["Unsupported-claim list", "Verification queue", "Revision notes"],
    stack: ["Text extraction", "LLM review", "Manual verification"],
    notes: "Planned. It should not auto-approve claims.",
  },
  {
    slug: "market-map-agent",
    name: "Market Map Agent",
    status: "Planned",
    problem: "Market maps need consistent categories before they become useful research shelves.",
    whatItDoes: "Will help organize protocols, products, and questions into neutral map drafts.",
    inputs: ["Protocol list", "Category notes", "Open questions"],
    outputs: ["Map draft", "Category gaps", "Research backlog"],
    stack: ["Spreadsheet workflow", "Manual review", "Markdown"],
    notes: "Planned. Map drafts remain placeholders until Yash adds source-backed evidence.",
  },
];
