import type { Agent } from "../types/content";

export const agents: Agent[] = [
  {
    slug: "research-feed-agent",
    name: "Research Feed Agent",
    status: "Building",
    problem: "Research inputs arrive across feeds, docs, dashboards, and notes.",
    whatItDoes: "Organizes incoming research material into a review queue for Yash to triage manually.",
    inputs: ["Saved links", "Protocol docs", "Dashboard notes", "Manual tags"],
    outputs: ["Review queue", "Topic clusters", "Follow-up prompts"],
    stack: ["Python", "RSS/API connectors", "LLM summarization", "Manual review"],
    notes: "Building workflow. Not a live product.",
  },
  {
    slug: "protocol-memo-agent",
    name: "Protocol Memo Agent",
    status: "Building",
    problem: "Draft memos need a consistent structure before source-backed analysis is added.",
    whatItDoes: "Turns rough notes into a memo scaffold with thesis, evidence gaps, risk checklist, and source slots.",
    inputs: ["Raw notes", "Article outline", "Source list"],
    outputs: ["Memo scaffold", "Evidence gaps", "Risk checklist"],
    stack: ["Structured outputs", "Markdown", "Manual review"],
    notes: "Building. Draft output still requires human research and editing.",
  },
  {
    slug: "dashboard-research-agent",
    name: "Dashboard Builder Agent",
    status: "Building",
    problem: "Dashboard ideas need a repeatable spec before charts, source checks, or automation are added.",
    whatItDoes: "Uses Codex to turn a dashboard brief into a static/manual dashboard spec, source checklist, risk notes, and portfolio UI entry.",
    inputs: ["Dashboard brief", "Related memo", "Manual source links", "Static snapshot values"],
    outputs: ["Dashboard spec", "Static UI section", "Source checklist", "Future data-source gaps"],
    stack: ["Codex workflow", "TypeScript content objects", "Manual review", "Recharts for static trend only"],
    notes: "Phase 1 is a manual/static builder workflow. It is not live, not API-connected, and does not use a backend or database.",
  },
  {
    slug: "claim-checker-agent",
    name: "Claim Checker Agent",
    status: "Planned",
    problem: "Draft research claims need to be separated from sourced evidence.",
    whatItDoes: "Will flag unsupported claims and route them into a manual verification queue.",
    inputs: ["Draft memo", "Source notes", "Claim list"],
    outputs: ["Unsupported-claim list", "Verification queue", "Revision notes"],
    stack: ["Text extraction", "LLM review", "Manual verification"],
    notes: "Planned. It should not auto-approve claims.",
  },
  {
    slug: "market-map-agent",
    name: "Market Map Agent",
    status: "Planned",
    problem: "Market maps need consistent categories before they become useful research shelves.",
    whatItDoes: "Will help organize protocols, products, and questions into neutral map drafts.",
    inputs: ["Protocol list", "Category notes", "Open questions"],
    outputs: ["Map draft", "Category gaps", "Research backlog"],
    stack: ["Spreadsheet workflow", "Manual review", "Markdown"],
    notes: "Planned. Map drafts remain placeholders until Yash adds source-backed evidence.",
  },
];
