import type { Article, ArticleContentBlock, CoverArtMetadata } from "../types/content";

export const articleCoverPresets: Record<string, CoverArtMetadata> = {
  "Stablecoin Yield": { variant: "flows", colors: ["#0f3b25", "#32d583", "#7dd3fc"], label: "SY" },
  "DeFi Fixed Income": { variant: "grid", colors: ["#172554", "#60a5fa", "#34d399"], label: "FI" },
  "Consumer Crypto Finance": { variant: "orbits", colors: ["#064e3b", "#34d399", "#facc15"], label: "CF" },
  "Agent-Payment Infrastructure": { variant: "nodes", colors: ["#1e1b4b", "#a78bfa", "#32d583"], label: "AP" },
  "On-chain Market Structure": { variant: "blocks", colors: ["#450a0a", "#fb7185", "#f59e0b"], label: "MS" },
  "Protocol Revenue & Incentives": { variant: "grid", colors: ["#422006", "#f59e0b", "#32d583"], label: "PR" },
};

const usddPendleContent: ArticleContentBlock[] = [
  { type: "heading", text: "1. Intro" },
  {
    type: "paragraph",
    text: "USDD moving into Pendle matters because it changes the asset from a passive stablecoin position into something that can be analyzed through duration, liquidity, and yield-distribution mechanics.",
  },
  {
    type: "callout",
    label: "Core Thesis",
    text: "The Pendle listing is important if it turns USDD yield into a separable, liquid, and benchmarkable instrument rather than a static stablecoin carry trade.",
    tone: "accent",
  },
  { type: "heading", text: "2. Getting Into Pendle" },
  {
    type: "paragraph",
    text: "Pendle splits yield-bearing exposure into principal and yield components. For USDD, the relevant question is whether this creates a deeper market for term yield, or simply adds another wrapper around an already thin liquidity base.",
  },
  {
    type: "figure",
    title: "Pendle Market Structure",
    src: "/research/usdd-pendle/pendle-market-structure.png",
    alt: "Pendle market structure for USDD principal and yield token flows",
    caption: "Placeholder for a diagram showing how USDD yield exposure enters Pendle and splits into marketable components.",
    visual: "rate-spread",
  },
  {
    type: "paragraph",
    text: "The first diligence step is to separate product-market fit from headline yield. A useful listing should improve price discovery, duration expression, and exit liquidity for allocators.",
  },
  {
    type: "table",
    title: "Metrics To Track",
    columns: ["Metric", "What To Watch", "Why It Matters"],
    rows: [
      ["Pendle TVL", "Depth by maturity and pool", "Shows whether the market can absorb size"],
      ["Implied fixed APY", "Spread vs. comparable stablecoin yield", "Tests whether USDD risk is compensated"],
      ["Trading volume", "Daily turnover and bid depth", "Separates real demand from idle incentives"],
      ["Liquidity concentration", "Top LP share and pool dependency", "Flags fragility if liquidity is subsidized"],
    ],
  },
  {
    type: "checklist",
    title: "Early Listing Checklist",
    items: [
      { text: "Confirm the Pendle pool, maturity, and underlying yield source before treating quoted APY as investable.", level: "amber" },
      { text: "Track whether liquidity remains after launch incentives normalize.", level: "amber" },
      { text: "Compare implied yield with more established stablecoin yield venues.", level: "green" },
    ],
  },
  {
    type: "figure",
    title: "TVL And Revenue Path",
    src: "/research/usdd-pendle/tvl-revenue.png",
    alt: "USDD TVL and revenue trend placeholder",
    caption: "Placeholder for TVL, revenue, and yield-distribution evidence once the chart export is ready.",
    visual: "reserve-flow",
  },
  { type: "heading", text: "3. Smart Allocator Mechanism" },
  {
    type: "paragraph",
    text: "The Smart Allocator Mechanism is the center of the memo because it determines whether yield is predictable, diversified, and defensible. The market should care less about the top-line APY and more about how that APY is sourced.",
  },
  {
    type: "figure",
    title: "Income Statement View",
    src: "/research/usdd-pendle/income-statement.png",
    alt: "USDD income statement placeholder",
    caption: "Placeholder for income statement or yield-source bridge.",
    visual: "rate-spread",
  },
  {
    type: "paragraph",
    text: "A stronger allocator design would show transparent venue selection, risk limits, liquidity buffers, and a clear policy for distributing or retaining income. Without that, a Pendle listing can amplify uncertainty by creating tradable claims on poorly understood yield.",
  },
  {
    type: "figure",
    title: "Allocator Distribution",
    src: "/research/usdd-pendle/allocator-distribution.png",
    alt: "USDD allocator distribution placeholder",
    caption: "Placeholder for allocator distribution across venues, reserves, and liquidity buffers.",
    visual: "market-map",
  },
  { type: "heading", text: "4. Current Allocation" },
  {
    type: "table",
    title: "Allocation Diligence Frame",
    columns: ["Bucket", "Current Read", "Diligence Question"],
    rows: [
      ["Reserve/liquidity buffer", "Needs source-backed confirmation", "Can redemptions be handled without forced unwinds?"],
      ["Yield venues", "Needs venue-level disclosure", "Is yield diversified or dependent on one strategy?"],
      ["Pendle liquidity", "Early market to monitor", "Does depth persist after incentives?"],
      ["Risk controls", "Policy clarity required", "Who can rebalance and under what constraints?"],
    ],
  },
  {
    type: "checklist",
    title: "Risk Checklist",
    items: [
      { text: "Liquidity risk: Pendle depth may not match headline TVL during stress.", level: "amber" },
      { text: "Source risk: allocator yield quality depends on venue-level transparency.", level: "red" },
      { text: "Duration risk: fixed-yield buyers inherit exit risk before maturity.", level: "amber" },
      { text: "Incentive risk: launch rewards can mask organic demand.", level: "amber" },
      { text: "Stablecoin risk: USDD-specific peg and reserve assumptions need independent verification.", level: "red" },
    ],
  },
  { type: "heading", text: "5. My Take" },
  {
    type: "paragraph",
    text: "My base case is constructive but conditional. The Pendle listing is strategically useful if it turns USDD yield into a more transparent market signal. It is not enough by itself to underwrite the asset without allocator-level evidence.",
  },
  {
    type: "quote",
    text: "The question is not whether Pendle can make USDD yield tradable. The question is whether tradability improves underwriting quality.",
    attribution: "Yash Khandelwal",
  },
  {
    type: "sources",
    items: ["USDD documentation", "Pendle market pages", "Protocol reserve disclosures", "On-chain pool data"],
  },
];

const stablecoinYieldContent: ArticleContentBlock[] = [
  { type: "heading", text: "1. Background & Context" },
  {
    type: "paragraph",
    text: "Since 2022, stablecoins have become the dominant on-chain savings instrument, with more than $160B in circulating supply as of Q4 2024. Most holders still treat their yield as equivalent to a money market fund, even though the risk stack is different.",
  },
  {
    type: "figure",
    title: "Reserve Flow Map",
    alt: "Abstract reserve flow map for stablecoin yield mechanics",
    caption: "A figure block can sit directly between two paragraphs. If a real src is not provided, the renderer shows this clean abstract placeholder.",
    visual: "reserve-flow",
  },
  {
    type: "paragraph",
    text: "This memo dissects the four major stablecoin yield archetypes: fiat-backed reserves, overcollateralized crypto-backed savings rates, synthetic yield-bearing dollars, and protocol incentive overlays. Each source should be priced as its own risk instrument.",
  },
  {
    type: "callout",
    label: "One-line Conclusion",
    text: "Stablecoin yield is not risk-free. It is risk-deferred, and the market often prices those risks as if they are interchangeable.",
    tone: "accent",
  },
  { type: "heading", text: "2. Mechanism Deep Dive" },
  {
    type: "table",
    title: "Yield Source Comparison - Q4 2024",
    columns: ["Protocol", "Yield Source", "Current APY", "Risk Type"],
    rows: [
      ["USDC (Circle)", "T-bill reserve", "~5.1%", "Custodial"],
      ["sDAI (Sky)", "DSR policy rate", "~4.9%", "Governance"],
      ["USDe (Ethena)", "Perp funding", "~8.2%", "Funding rate"],
      ["USDM (Mountain)", "T-bill + liquidity", "~5.0%", "Mixed"],
    ],
  },
  { type: "heading", text: "3. Data Analysis" },
  {
    type: "figure",
    title: "DSR vs. Fed Funds Rate",
    alt: "Abstract rate spread visualization for DSR and Fed Funds comparison",
    caption: "Placeholder for a chart image, Dune export, or custom research graphic.",
    visual: "rate-spread",
  },
  {
    type: "paragraph",
    text: "The DSR has tracked Fed Funds within a narrow band for much of the current rate cycle. That suggests tight policy transmission, but it also means holders inherit a governance-controlled version of benchmark-rate exposure.",
  },
  {
    type: "checklist",
    title: "Risk Checklist",
    items: [
      { text: "Custodial risk: fiat reserves are high quality, but not the same as self-custody.", level: "amber" },
      { text: "Smart contract risk: mature modules still require explicit failure-mode modeling.", level: "green" },
      { text: "Funding rate risk: synthetic stablecoin yield can collapse when perp markets invert.", level: "red" },
      { text: "Governance risk: benchmark yields can change faster than passive holders expect.", level: "amber" },
      { text: "Depeg risk: all dollar wrappers can become liquidity claims under stress.", level: "amber" },
    ],
  },
  {
    type: "quote",
    text: "USDe at 8% and sDAI at 5% do not simply carry 3% of difference in return. They carry structurally different risk types.",
    attribution: "Yash Khandelwal, November 2024",
  },
  {
    type: "sources",
    items: [
      "Sky/MakerDAO DSR Documentation",
      "Ethena Labs: USDe Mechanism Paper",
      "Defillama: Stablecoin TVL Dashboard",
      "Federal Reserve H.15 Selected Interest Rates",
      "Circle: USDC Reserve Reports Q3 2024",
    ],
  },
];

export const articles: Article[] = [
  {
    slug: "usdd-pendle-investment-memo",
    title: "USDD Investment Memo: Why the Pendle Listing Matters",
    thesis: "USDD entering Pendle matters if it makes yield, duration, and allocator risk easier to price instead of simply adding another incentive-driven market.",
    tags: ["USDD", "Pendle", "Stablecoins", "Yield"],
    date: "2025-01-20",
    readTime: 12,
    status: "Memo",
    category: "Stablecoin Yield",
    featured: true,
    conclusion: "The Pendle listing is bullish only if it improves transparency around allocator yield and creates durable liquidity beyond launch incentives.",
    coverArt: { variant: "flows", colors: ["#0b2f1e", "#32d583", "#facc15"], label: "UP" },
    content: usddPendleContent,
  },
  {
    slug: "stablecoin-yield-mechanics",
    title: "Stablecoin Yield Mechanics: How USDC Earns Without Risk (Until It Doesn't)",
    thesis: "Real yield in stablecoins flows from T-bill reserves, lending spreads, and liquidity mining - each carrying distinct risk profiles that most holders ignore.",
    tags: ["Stablecoins", "Yield", "USDC", "Risk"],
    date: "2024-11-18",
    readTime: 14,
    status: "Memo",
    category: "Stablecoin Yield",
    featured: true,
    conclusion: "Stablecoin yield is not risk-free. It is risk-deferred, and the market often prices those risks as if they are interchangeable.",
    content: stablecoinYieldContent,
  },
  {
    slug: "aave-rate-market",
    title: "Aave v3's Interest Rate Model: A Fixed Income Lens",
    thesis: "Aave's utilization-based rate curve is structurally equivalent to a floating-rate bond market - and pricing it that way reveals systematic mispricings.",
    tags: ["Aave", "DeFi", "Fixed Income", "Rates"],
    date: "2024-10-31",
    readTime: 18,
    status: "Memo",
    category: "DeFi Fixed Income",
    featured: true,
  },
  {
    slug: "agent-payments-x402",
    title: "x402: The HTTP Status Code That Unlocks Machine Commerce",
    thesis: "The x402 payment-required protocol enables autonomous agents to pay for APIs mid-request, collapsing the gap between AI capability and economic agency.",
    tags: ["AI Agents", "x402", "Payments", "Infrastructure"],
    date: "2024-12-02",
    readTime: 11,
    status: "Article",
    category: "Agent-Payment Infrastructure",
    featured: true,
  },
  {
    slug: "dex-market-structure",
    title: "DEX Market Structure 2024: Who Actually Provides Liquidity?",
    thesis: "Passive LPs are losing ground to professional market-makers who treat AMMs as structured products - changing who captures spread and how.",
    tags: ["DEX", "AMMs", "Market Structure", "LPs"],
    date: "2024-09-15",
    readTime: 22,
    status: "Market Map",
    category: "On-chain Market Structure",
  },
  {
    slug: "protocol-revenue-map",
    title: "Protocol Revenue Taxonomy: A Map of On-chain Cash Flows",
    thesis: "Most protocols generate revenue in 3 structural ways - fee take, spread capture, or inflation funding - and conflating them distorts valuation.",
    tags: ["Revenue", "Tokenomics", "Valuation", "DeFi"],
    date: "2024-08-22",
    readTime: 9,
    status: "Market Map",
    category: "Protocol Revenue & Incentives",
  },
  {
    slug: "sky-savings-rate",
    title: "Sky (MakerDAO) Savings Rate: DSR as the DeFi Risk-Free Rate",
    thesis: "The DSR functions as DeFi's policy rate benchmark - when it rises, capital reallocates across the entire ecosystem.",
    tags: ["MakerDAO", "Sky", "DSR", "Rates"],
    date: "2024-11-05",
    readTime: 8,
    status: "Notes",
    category: "Stablecoin Yield",
  },
  {
    slug: "pendle-fixed-yield",
    title: "Pendle Finance: Tokenizing Time Value in DeFi",
    thesis: "Pendle's yield-stripping mechanism creates genuinely novel instruments - but liquidity fragmentation across maturities caps institutional adoption.",
    tags: ["Pendle", "Yield", "Fixed Income", "DeFi"],
    date: "2024-10-12",
    readTime: 16,
    status: "Memo",
    category: "DeFi Fixed Income",
  },
  {
    slug: "mev-anatomy",
    title: "MEV Anatomy: A Taxonomy of Value Extraction on Ethereum",
    thesis: "MEV isn't noise - it's a structural feature of public mempools. Understanding its forms is prerequisite to modeling any on-chain market.",
    tags: ["MEV", "Ethereum", "Market Structure", "Arbitrage"],
    date: "2024-07-30",
    readTime: 20,
    status: "Article",
    category: "On-chain Market Structure",
  },
];
