import type { Article, ArticleContentBlock, ArticleFigureVisual, CoverArtMetadata } from "../types/content";

export const articleCoverPresets: Record<string, CoverArtMetadata> = {
  "Stablecoin Yield": { variant: "flows", colors: ["#0f3b25", "#32d583", "#7dd3fc"], label: "SY" },
  "DeFi Fixed Income": { variant: "grid", colors: ["#172554", "#60a5fa", "#34d399"], label: "FI" },
  "Consumer Crypto": { variant: "orbits", colors: ["#064e3b", "#34d399", "#facc15"], label: "CC" },
  "Prediction Markets": { variant: "blocks", colors: ["#3b0764", "#a78bfa", "#60a5fa"], label: "PM" },
  "Market Structure": { variant: "blocks", colors: ["#450a0a", "#fb7185", "#f59e0b"], label: "MS" },
  "Agent Infrastructure": { variant: "nodes", colors: ["#1e1b4b", "#a78bfa", "#32d583"], label: "AI" },
  "Protocol Research": { variant: "grid", colors: ["#422006", "#f59e0b", "#32d583"], label: "PR" },
};

const placeholderContent = (topic: string, visual: ArticleFigureVisual = "reserve-flow"): ArticleContentBlock[] => [
  {
    type: "paragraph",
    text: `${topic} is a placeholder research entry. Yash will add the source-backed memo, evidence, and conclusions later.`,
  },
  {
    type: "callout",
    label: "Research Placeholder",
    text: "This entry is intentionally unfinished and should not be read as a completed article or investment conclusion.",
    tone: "info",
  },
  {
    type: "diagram-placeholder",
    title: "Evidence Map Placeholder",
    caption: "Add the working diagram, chart, or evidence map when the research is ready.",
    visual,
  },
  {
    type: "sources",
    items: ["Source list to be added"],
  },
];

const usddPendleContent: ArticleContentBlock[] = [
  { type: "heading", text: "Opening Thesis" },
  {
    type: "paragraph",
    text: "Pendle markets are capacity allocated. This means Pendle does not add every yield-bearing asset that wants a market. It chooses assets that are worth bringing into its fixed-yield ecosystem.",
  },
  {
    type: "paragraph",
    text: "And that matters because Pendle is one of DeFi's main yield-trading platforms. It lets users trade spot yield, earn fixed yield, or take long exposure to future yield through PT and YT markets.",
  },
  {
    type: "callout",
    label: "Opening Thesis",
    text: "When a stablecoin gets a Pendle market, it usually means one thing: the market believes the yield is mature enough to be priced, traded, and structured.",
    tone: "accent",
  },
  {
    type: "paragraph",
    text: "USDD is the latest stablecoin to enter that category.",
  },
  { type: "heading", text: "Getting Into Pendle" },
  {
    type: "paragraph",
    text: "The short list of stablecoins already active on Pendle - such as sUSDS, sUSDe, sFRAX, and USDY - earned their place because they have a few things in common.",
  },
  {
    type: "checklist",
    title: "What Pendle Stablecoin Markets Tend To Require",
    items: [
      { text: "A yield engine that fixed-rate capital is willing to take exposure to.", level: "green" },
      { text: "Proper TVL depth.", level: "green" },
      { text: "Audited contracts.", level: "green" },
      { text: "Clear redemption mechanics.", level: "green" },
      { text: "Demand from sophisticated DeFi users.", level: "green" },
    ],
  },
  {
    type: "paragraph",
    text: "USDD is now trying to sit in the same group. The current numbers for @usddio look like this:",
  },
  {
    type: "table",
    title: "Current USDD Metrics",
    columns: ["Metric", "Value"],
    rows: [
      ["Supply", "~$1.4B"],
      ["On-chain collateral", "~$2.12B"],
      ["Over-collateralization", "~150%"],
      ["Cumulative earnings", "~$18.5M"],
      ["Blended APY", "3.56%"],
      ["Smart Allocator deployment", "~$830M across Spark, Aave, and Morpho"],
      ["Annualized fees/revenue", "$5.91M on DeFiLlama"],
      ["TVL", "$1.30B on DeFiLlama"],
    ],
  },
  {
    type: "paragraph",
    text: "The income trend is also worth noting. USDD's quarterly earnings have moved from $279.46K in Q2 2025 to $1.01M in Q2 2026. There was a small dip between Q3 and Q4 2025, but the broader trend is clearly higher.",
  },
  {
    type: "figure",
    title: "USDD TVL And Revenue",
    src: "/research/usdd-pendle/tvl-revenue.png",
    alt: "USDD DeFiLlama TVL and fees revenue chart",
    caption: "PDF visual showing USDD TVL and revenue metrics on DeFiLlama.",
    visual: "reserve-flow",
  },
  {
    type: "figure",
    title: "USDD Income Statement",
    src: "/research/usdd-pendle/income-statement.png",
    alt: "USDD income statement table from the memo",
    caption: "PDF visual showing quarterly USDD earnings and revenue line items.",
    visual: "rate-spread",
  },
  {
    type: "paragraph",
    text: "That is important because Pendle users do not only look at headline APY. They care about whether the yield engine has depth, repeatability, and enough revenue history to support a fixed-yield market.",
  },
  { type: "heading", text: "Smart Allocator Mechanism" },
  {
    type: "paragraph",
    text: "The basic idea is straightforward. USDD has reserves backing the stablecoin. Instead of letting those reserves sit idle, the protocol deploys part of that capital into selected DeFi yield venues and sends the net returns back to users through sUSDD.",
  },
  {
    type: "paragraph",
    text: "sUSDD works through an ERC-4626 vault that revalues continuously. If you hold sUSDD, your token's redemption value increases as the underlying reserve strategies earn yield.",
  },
  {
    type: "checklist",
    title: "Smart Allocator Flow",
    items: [
      { text: "USDD reserves.", level: "green" },
      { text: "Deployed into selected DeFi yield venues.", level: "green" },
      { text: "Earn lending interest and platform rewards.", level: "green" },
      { text: "Small risk reserve is kept.", level: "amber" },
      { text: "Remaining yield flows back to sUSDD holders.", level: "green" },
    ],
  },
  {
    type: "paragraph",
    text: "USDD's docs describe Smart Allocator as a fully on-chain, transparent, risk-controlled investment strategy built to create self-sustaining yield and reduce reliance on external subsidies.",
  },
  {
    type: "paragraph",
    text: "That last part is important. USDD is not trying to rely only on temporary campaign rewards. The goal is to build a reserve engine that keeps generating yield even after the campaign ends.",
  },
  {
    type: "table",
    title: "Current Allocation",
    columns: ["Venue", "Share", "Approximate Capital"],
    rows: [
      ["@sparkdotfi", "86.55%", "~$714M"],
      ["@aave", "13.5%", "~$112.6M"],
      ["@Morpho", "0.37%", "~$3M"],
    ],
  },
  {
    type: "figure",
    title: "Allocated Asset Distribution",
    src: "/research/usdd-pendle/allocator-distribution.png",
    alt: "USDD Smart Allocator distribution across Spark, Aave, and Morpho",
    caption: "PDF visual showing the Smart Allocator distribution by venue.",
    visual: "market-map",
  },
  {
    type: "paragraph",
    text: "This also explains why USDD fits naturally into the same conversation as sUSDS. sUSDS uses the Sky Savings Rate, where USDS holders capture yield from the broader Sky/Spark system. sUSDD follows a similar vault-based logic, but its yield comes from USDD reserves being deployed through Smart Allocator.",
  },
  {
    type: "figure",
    title: "Sky Savings Rate Context",
    src: "/research/usdd-pendle/sky-savings-rate.png",
    alt: "Sky Savings Rate interface shown in the USDD memo",
    caption: "PDF visual used as context for the sUSDS savings-rate comparison.",
    visual: "rate-spread",
  },
  { type: "heading", text: "Is USDD Yield Fixed or Dynamic?" },
  {
    type: "paragraph",
    text: "USDD's base yield is dynamic. It is not a fixed rate.",
  },
  {
    type: "checklist",
    title: "Dynamic APY Inputs",
    items: [
      { text: "A 7-day moving average of mainstream yield-bearing stablecoin yields.", level: "green" },
      { text: "The Fed funds rate.", level: "green" },
      { text: "A competitive premium to keep sUSDD attractive against peers.", level: "green" },
    ],
  },
  {
    type: "figure",
    title: "Dynamic APY",
    src: "/research/usdd-pendle/dynamic-apy.png",
    alt: "Dynamic APY examples across Tron, Ethereum, and BNB Chain",
    caption: "PDF visual showing Dynamic APY examples across supported chains.",
    visual: "rate-spread",
  },
  {
    type: "paragraph",
    text: "This means the yield is designed to move with the broader stablecoin yield environment. If market yields compress, sUSDD yield can compress. If lending markets become more attractive, sUSDD yield can move higher. So the yield is not static - it is market-aware.",
  },
  {
    type: "paragraph",
    text: "But once sUSDD enters Pendle, users get different ways to interact with that yield:",
  },
  {
    type: "table",
    title: "Yield Layer Comparison",
    columns: ["Layer", "Yield Type", "Static/Dynamic?", "Explanation"],
    rows: [
      ["Base sUSDD yield", "Smart Allocator yield", "Dynamic", "Depends on reserve deployment returns, lending rates, risk reserve, and market conditions"],
      ["PT-sUSDD on Pendle", "Fixed yield if held to maturity", "Fixed after entry", "User buys PT at a discount and redeems at full value at maturity"],
      ["YT-sUSDD / LP", "Variable yield + incentives", "Dynamic", "Depends on sUSDD yield, Pendle pricing, trading fees, incentives, and time to maturity"],
    ],
  },
  {
    type: "paragraph",
    text: "This is the key distinction: sUSDD itself has dynamic yield. PT-sUSDD can turn that into fixed yield. YT-sUSDD gives users leveraged exposure to future yield. LP positions give users fees, incentives, and exposure to the market structure.",
  },
  {
    type: "paragraph",
    text: "One more detail matters for Pendle: sUSDD is fully redeemable for USDD. There is no lockup, no withdrawal restriction, and no waiting period. That is important because PT and YT pricing depends on clean redemption mechanics. If the underlying asset cannot be redeemed properly, the entire fixed-yield market becomes harder to price. sUSDD's design fits that requirement.",
  },
  {
    type: "figure",
    title: "sUSDD Redemption Value",
    src: "/research/usdd-pendle/susdd-redemption-value.png",
    alt: "sUSDD redemption value chart",
    caption: "PDF visual showing sUSDD redemption value over time.",
    visual: "reserve-flow",
  },
  { type: "heading", text: "Why the Pendle Listing Matters" },
  {
    type: "paragraph",
    text: "Pendle is selective about stablecoin yield markets. PT and YT pricing requires the underlying yield to be stable enough for traders to take fixed-rate positions on it months in advance. Assets whose yield is unclear, temporary, or too fragile usually do not make sense for this kind of market.",
  },
  {
    type: "paragraph",
    text: "Look at what sUSDD's competitors on Pendle have in common:",
  },
  {
    type: "table",
    title: "Pendle Stablecoin Yield Peers",
    columns: ["Asset", "Yield Mechanism"],
    rows: [
      ["sUSDS", "Earned its market through the Sky Savings Rate, backed by lending, Treasury exposure, and the broader Sky/Spark system."],
      ["sUSDe", "Earned its market by running a basis trade that captures funding paid by leveraged traders."],
      ["USDY", "Earned its market by giving on-chain users exposure to tokenized U.S. Treasury yield."],
    ],
  },
  {
    type: "paragraph",
    text: "Each peer earns yield through a different mechanism. sUSDD's edge is that it spreads its reserve deployment across Spark, Aave, and Morpho instead of relying on only one yield model.",
  },
  {
    type: "paragraph",
    text: "For users already holding sUSDS, sUSDe, or other yield-bearing stablecoins on Pendle, sUSDD gives them a new way to diversify within the same platform. That is the real point of the listing.",
  },
  {
    type: "callout",
    label: "Listing Value",
    text: "USDD is not just adding liquidity. It is entering DeFi's fixed-income layer.",
    tone: "accent",
  },
  { type: "heading", text: "Strategic Value Unlocked by the Listing" },
  {
    type: "paragraph",
    text: "Pendle gives users three ways to earn from sUSDD, depending on what they want.",
  },
  {
    type: "table",
    title: "sUSDD Pendle Position Types",
    columns: ["Position", "Use Case", "PDF Description"],
    rows: [
      ["PT-sUSDD", "Fixed Yield", "For users who want fixed, predictable yield. Users buy PT-sUSDD at a discount, hold it until maturity, and redeem it at full value. The difference becomes the locked-in yield."],
      ["YT-sUSDD", "Variable Yield", "For users who want more upside. YT holders collect the variable yield side of sUSDD, plus campaign rewards including base APY, the $300K+ reward pool, Pendle boosts, and additional campaign incentives."],
      ["LP-sUSDD", "Liquidity Provider", "For users who do not want to fully pick a side. LPs provide liquidity to the PT/YT market and earn from trading fees, PENDLE rewards, yield generated by the pool's mix of SY and PT positions, and campaign incentives."],
    ],
  },
  {
    type: "paragraph",
    text: "YT payoff depends on how yield moves during the 91-day window, so YT is the higher-risk, higher-reward side of the trade. PT is the conservative side of the Pendle market.",
  },
  {
    type: "checklist",
    title: "What Moves Pendle Yield",
    items: [
      { text: "Time left to maturity.", level: "amber" },
      { text: "Market expectations around future yield.", level: "amber" },
      { text: "Capital flows between PT and YT.", level: "amber" },
      { text: "Incentives and trading activity.", level: "amber" },
    ],
  },
  {
    type: "paragraph",
    text: "PT brings fixed-yield capital. YT brings yield speculators. LP brings market makers and farmers. Add composability on top, and one Pendle listing starts doing the work of three different products.",
  },
  { type: "heading", text: "The Composability Unlock" },
  {
    type: "paragraph",
    text: "There is also a less obvious benefit here: composability. Once an asset has a working Pendle market, it can become part of broader DeFi strategies.",
  },
  {
    type: "checklist",
    title: "Where sUSDD Can Be Used",
    items: [
      { text: "Fixed-yield strategies.", level: "green" },
      { text: "Looping strategies.", level: "green" },
      { text: "Structured products.", level: "green" },
      { text: "Yield vaults.", level: "green" },
      { text: "Treasury strategies.", level: "green" },
      { text: "Portfolio diversification inside Pendle.", level: "green" },
    ],
  },
  {
    type: "paragraph",
    text: "This is why the listing matters beyond the 91-day campaign. The campaign brings attention. But the Pendle market gives sUSDD a place inside DeFi's yield-trading stack.",
  },
  { type: "heading", text: "Where sUSDD Fits in the Stablecoin Yield Category" },
  {
    type: "paragraph",
    text: "Stablecoin yield can be split into a few main buckets.",
  },
  {
    type: "table",
    title: "Stablecoin Yield Buckets",
    columns: ["Bucket", "Example", "Yield Source"],
    rows: [
      ["Savings-rate stablecoins", "sUSDS", "The Sky Savings Rate and the broader Sky/Spark ecosystem."],
      ["Basis-trade stablecoins", "sUSDe", "Funding rates and basis trades, usually through long spot and short perpetual futures exposure."],
      ["RWA / Treasury stablecoins", "USDY", "Tokenized exposure to U.S. Treasury-style assets."],
      ["Reserve-deployment stablecoins", "sUSDD", "Deploying reserves into DeFi lending venues and distributing the returns through a vault token."],
    ],
  },
  {
    type: "paragraph",
    text: "USDD is not trying to be another synthetic dollar. It is not trying to be only a tokenized Treasury product. It is trying to become a reserve-backed DeFi yield stablecoin.",
  },
  {
    type: "checklist",
    title: "What Matters Most",
    items: [
      { text: "More collateral than supply: USDD has around $2.12B in collateral backing around $1.4B in supply, giving it roughly 150% over-collateralization.", level: "green" },
      { text: "Three position types from one market: PT, YT, and LP attract different kinds of capital and broaden who sUSDD can reach.", level: "green" },
      { text: "APY linked to market conditions: the Dynamic APY mechanism adjusts to stablecoin yield markets and traditional rate benchmarks instead of relying only on temporary incentives.", level: "green" },
    ],
  },
  {
    type: "figure",
    title: "System Backing",
    src: "/research/usdd-pendle/system-backing.png",
    alt: "USDD system backing chart",
    caption: "PDF visual showing USDD system backing categories over time.",
    visual: "reserve-flow",
  },
  {
    type: "paragraph",
    text: "Across roughly $830M in deployed reserves, Smart Allocator has generated around $18.5M in cumulative earnings, visible on-chain. The real question is whether this base earnings engine keeps working after the incentives fade.",
  },
  { type: "heading", text: "Early Traction on Pendle" },
  {
    type: "paragraph",
    text: "The early numbers for the sUSDD Pendle market are strong. The pool has already grown to $13M+ in TVL, with around $8M deposited on day one.",
  },
  {
    type: "table",
    title: "Current Campaign APYs",
    columns: ["Position", "APY"],
    rows: [
      ["YT", "13.53%"],
      ["PT", "7.88%"],
      ["LP", "9.31%"],
    ],
  },
  {
    type: "figure",
    title: "Pendle Market",
    src: "/research/usdd-pendle/pendle-market.png",
    alt: "sUSDD market row on Pendle showing liquidity and APY data",
    caption: "PDF visual showing the sUSDD Pendle market and position-level data.",
    visual: "rate-spread",
  },
  {
    type: "paragraph",
    text: "The LP APY breaks down across three sources: PENDLE token rewards distributed to the pool, trading fees from user swaps, and yield generated by the pool's mix of SY and PT positions.",
  },
  {
    type: "paragraph",
    text: "For context, USDG's Pendle campaign opened with around $60K in exclusive incentives over six weeks. sUSDD starts with $300K+ in rewards over 91 days, plus a 30% Pendle reward boost and additional TRX airdrop incentives.",
  },
  {
    type: "paragraph",
    text: "PT buyers are getting around 7.88% for 91 days - noticeably higher than base sUSDD yield. YT and LP holders get the campaign rewards layered on top.",
  },
  {
    type: "callout",
    label: "Base Yield Versus Campaign Rewards",
    text: "Base yield is the sustainable engine. Campaign rewards are the accelerator. The investment case should not depend only on the accelerator.",
    tone: "warning",
  },
  { type: "heading", text: "Risk Checklist" },
  {
    type: "paragraph",
    text: "The setup is strong, but it is not risk-free.",
  },
  {
    type: "checklist",
    title: "Risk Checklist",
    items: [
      { text: "Allocator concentration: Smart Allocator is diversified across Spark, Aave, and Morpho, but it is still heavily weighted toward Spark at 86.55%. That means the yield is more dependent on one major venue than the headline diversification might suggest.", level: "amber" },
      { text: "Post-campaign yield: the Pendle campaign makes the APY look attractive, but the real test starts when the campaign ends. If capital stays after the rewards fade, that is a strong signal. If TVL falls sharply, then a large part of the traction was incentive-driven.", level: "amber" },
      { text: "Yield compression: because USDD's base yield is dynamic, it can move lower if stablecoin lending rates compress or if market-wide yields fall.", level: "amber" },
      { text: "Peg and redemption depth: sUSDD is redeemable for USDD, but the broader system still depends on collateral quality, liquidity, liquidation execution, and market confidence.", level: "red" },
      { text: "Smart contract and integration risk: Pendle, sUSDD, Smart Allocator, and the underlying venues all add layers of technical exposure.", level: "red" },
    ],
  },
  { type: "heading", text: "My Take" },
  {
    type: "paragraph",
    text: "USDD has been a stablecoin staple on TRON for a long time. Now it is trying to become something larger: a multichain, yield-generating stablecoin that can compete inside DeFi's fixed-income layer.",
  },
  {
    type: "paragraph",
    text: "Smart Allocator is the core of that shift. It puts USDD reserves to work across blue-chip DeFi venues and routes the yield back through sUSDD. Pendle then takes that yield and turns it into three different markets: fixed yield through PT, variable yield through YT, and fee and incentive yield through LP.",
  },
  {
    type: "paragraph",
    text: "That is why this listing matters. It gives USDD distribution, composability, and a place inside one of DeFi's most important yield markets.",
  },
  {
    type: "checklist",
    title: "What To Track",
    items: [
      { text: "Smart Allocator is still heavily weighted toward Spark.", level: "amber" },
      { text: "The long-term opportunity depends on how USDD performs after the campaign.", level: "amber" },
      { text: "The base yield can move as market rates change.", level: "amber" },
      { text: "The strongest Pendle APYs include incentives, not just organic yield.", level: "amber" },
    ],
  },
  {
    type: "paragraph",
    text: "So it is important to separate the short-term trade from the long-term thesis. The short-term trade is the Pendle campaign. The long-term thesis is Smart Allocator.",
  },
  {
    type: "paragraph",
    text: "If Smart Allocator continues generating real income after incentives fade, then sUSDD can become a persistent part of DeFi's stablecoin yield stack. If most of the demand is campaign-driven, the market will show that once rewards slow down.",
  },
  {
    type: "callout",
    label: "Closing Take",
    text: "USDD has built a reserve engine that generates real income, and Pendle gives that yield a market. That is what makes this listing worth watching.",
    tone: "accent",
  },
];

export const articles: Article[] = [
  {
    slug: "usdd-pendle-investment-memo",
    title: "USDD Investment Memo: Why the Pendle Listing Matters",
    thesis: "USDD's Pendle market matters because it brings the stablecoin's yield into DeFi's fixed-yield ecosystem, where it can be priced, traded, and structured.",
    tags: ["USDD", "Pendle", "Stablecoins", "Yield"],
    date: "2025-01-20",
    readTime: 14,
    status: "Memo",
    category: "Stablecoin Yield",
    featured: true,
    conclusion: "USDD has built a reserve engine that generates real income, and Pendle gives that yield a market.",
    coverArt: { variant: "flows", colors: ["#0b2f1e", "#32d583", "#facc15"], label: "UP" },
    content: usddPendleContent,
  },
  {
    slug: "stablecoin-sandwich-dollar-journey",
    title: "The Stablecoin Sandwich: Anatomy of the Dollar's Journey",
    thesis: "Placeholder for a future memo on how stablecoin dollars move through issuers, venues, and yield wrappers.",
    tags: ["Stablecoins", "Yield", "Cash Flows"],
    date: "2025-01-10",
    readTime: 8,
    status: "Draft",
    category: "Stablecoin Yield",
    featured: true,
    content: placeholderContent("The Stablecoin Sandwich", "reserve-flow"),
  },
  {
    slug: "prediction-market-making-probability-space",
    title: "Market Making for Prediction Markets: A Probability-Space Approach",
    thesis: "Placeholder for a future research note on prediction-market liquidity and market-making frameworks.",
    tags: ["Prediction Markets", "Market Making", "Liquidity"],
    date: "2025-01-08",
    readTime: 7,
    status: "Researching",
    category: "Prediction Markets",
    content: placeholderContent("Market Making for Prediction Markets", "market-map"),
  },
  {
    slug: "consumer-crypto-finance-map",
    title: "Consumer Crypto Finance Map",
    thesis: "Placeholder map for consumer crypto finance products, rails, and unanswered research questions.",
    tags: ["Consumer Crypto", "Finance", "Market Map"],
    date: "2025-01-05",
    readTime: 6,
    status: "Map",
    category: "Consumer Crypto",
    content: placeholderContent("Consumer Crypto Finance Map", "market-map"),
  },
  {
    slug: "agent-payment-infrastructure-beyond-x402",
    title: "Agent Payment Infrastructure Beyond x402",
    thesis: "Placeholder for research on agent-payment infrastructure, payment flows, and open protocol questions.",
    tags: ["Agents", "Payments", "Infrastructure"],
    date: "2025-01-03",
    readTime: 6,
    status: "Researching",
    category: "Agent Infrastructure",
    featured: true,
    content: placeholderContent("Agent Payment Infrastructure", "agent-network"),
  },
  {
    slug: "protocol-revenue-incentive-durability",
    title: "Protocol Revenue vs Incentive Durability",
    thesis: "Placeholder memo for comparing protocol revenue, incentive design, and durability questions.",
    tags: ["Protocol Research", "Revenue", "Incentives"],
    date: "2024-12-20",
    readTime: 7,
    status: "Memo",
    category: "Protocol Research",
    content: placeholderContent("Protocol Revenue vs Incentive Durability", "rate-spread"),
  },
  {
    slug: "pendle-fixed-yield-markets",
    title: "Pendle Fixed-Yield Markets",
    thesis: "Placeholder for a future fixed-income research note connected to the USDD/Pendle memo.",
    tags: ["Pendle", "Fixed Yield", "DeFi"],
    date: "2024-12-12",
    readTime: 7,
    status: "Draft",
    category: "DeFi Fixed Income",
    content: placeholderContent("Pendle Fixed-Yield Markets", "rate-spread"),
  },
  {
    slug: "on-chain-market-structure-notes",
    title: "On-chain Market Structure Notes",
    thesis: "Placeholder notes for market-structure questions that need source-backed research before publication.",
    tags: ["Market Structure", "Liquidity", "Research Notes"],
    date: "2024-12-02",
    readTime: 5,
    status: "Researching",
    category: "Market Structure",
    content: placeholderContent("On-chain Market Structure Notes", "market-map"),
  },
];
