import type { Article, ArticleContentBlock, ArticleFigureVisual, CoverArtMetadata } from "../types/content";

export const articleCoverPresets: Record<string, CoverArtMetadata> = {
  "Stablecoin Yield": { variant: "flows", colors: ["#0f3b25", "#32d583", "#7dd3fc"], label: "SY" },
  "DeFi Fixed Income": { variant: "grid", colors: ["#172554", "#60a5fa", "#34d399"], label: "FI" },
  "Consumer Crypto": { variant: "orbits", colors: ["#064e3b", "#34d399", "#facc15"], label: "CC" },
  "Prediction Markets": { variant: "blocks", colors: ["#3b0764", "#a78bfa", "#60a5fa"], label: "PM" },
  "Market Structure": { variant: "blocks", colors: ["#450a0a", "#fb7185", "#f59e0b"], label: "MS" },
  "Agent Infrastructure": { variant: "nodes", colors: ["#1e1b4b", "#a78bfa", "#32d583"], label: "AI" },
  "Protocol Research": { variant: "grid", colors: ["#422006", "#f59e0b", "#32d583"], label: "PR" },
};

const placeholderContent = (topic: string, visual: ArticleFigureVisual = "reserve-flow"): ArticleContentBlock[] => [
  {
    type: "paragraph",
    text: `${topic} is a placeholder research entry. Yash will add the source-backed memo, evidence, and conclusions later.`,
  },
  {
    type: "callout",
    label: "Research Placeholder",
    text: "This entry is intentionally unfinished and should not be read as a completed article or investment conclusion.",
    tone: "info",
  },
  {
    type: "diagram-placeholder",
    title: "Evidence Map Placeholder",
    caption: "Add the working diagram, chart, or evidence map when the research is ready.",
    visual,
  },
  {
    type: "sources",
    items: ["Source list to be added"],
  },
];

const usddPendleContent: ArticleContentBlock[] = [
  { type: "heading", text: "1. Intro" },
  {
    type: "paragraph",
    text: "USDD moving into Pendle matters because it changes the asset from a passive stablecoin position into something that can be analyzed through duration, liquidity, and yield-distribution mechanics.",
  },
  {
    type: "callout",
    label: "Core Thesis",
    text: "The Pendle listing is important if it turns USDD yield into a separable, liquid, and benchmarkable instrument rather than a static stablecoin carry trade.",
    tone: "accent",
  },
  { type: "heading", text: "2. Getting Into Pendle" },
  {
    type: "paragraph",
    text: "Pendle splits yield-bearing exposure into principal and yield components. For USDD, the relevant question is whether this creates a deeper market for term yield, or simply adds another wrapper around an already thin liquidity base.",
  },
  {
    type: "figure",
    title: "Pendle Market Structure",
    src: "/research/usdd-pendle/pendle-market-structure.png",
    alt: "Pendle market structure for USDD principal and yield token flows",
    caption: "Placeholder for a diagram showing how USDD yield exposure enters Pendle and splits into marketable components.",
    visual: "rate-spread",
  },
  { type: "heading", text: "3. Smart Allocator Mechanism" },
  {
    type: "paragraph",
    text: "The Smart Allocator Mechanism is the center of the memo because it determines whether yield is predictable, diversified, and defensible. The market should care less about the top-line APY and more about how that APY is sourced.",
  },
  {
    type: "figure",
    title: "Income Statement View",
    src: "/research/usdd-pendle/income-statement.png",
    alt: "USDD income statement placeholder",
    caption: "Placeholder for income statement or yield-source bridge.",
    visual: "rate-spread",
  },
  {
    type: "paragraph",
    text: "A stronger allocator design would show transparent venue selection, risk limits, liquidity buffers, and a clear policy for distributing or retaining income. Without that, a Pendle listing can amplify uncertainty by creating tradable claims on poorly understood yield.",
  },
  {
    type: "figure",
    title: "Allocator Distribution",
    src: "/research/usdd-pendle/allocator-distribution.png",
    alt: "USDD allocator distribution placeholder",
    caption: "Placeholder for allocator distribution across venues, reserves, and liquidity buffers.",
    visual: "market-map",
  },
  { type: "heading", text: "4. Dynamic vs Fixed Yield" },
  {
    type: "paragraph",
    text: "This section keeps the draft focused on the difference between dynamic allocator yield and fixed-yield market pricing. It needs source-backed data before it becomes a conclusion.",
  },
  {
    type: "table",
    title: "Metrics To Track",
    columns: ["Metric", "What To Watch", "Why It Matters"],
    rows: [
      ["Pendle TVL", "Depth by maturity and pool", "Shows whether the market can absorb size"],
      ["Implied fixed APY", "Spread vs. comparable stablecoin yield", "Tests whether USDD risk is compensated"],
      ["Trading volume", "Daily turnover and bid depth", "Separates real demand from idle incentives"],
      ["Liquidity concentration", "Top LP share and pool dependency", "Flags fragility if liquidity is subsidized"],
    ],
  },
  {
    type: "figure",
    title: "TVL And Revenue Path",
    src: "/research/usdd-pendle/tvl-revenue.png",
    alt: "USDD TVL and revenue trend placeholder",
    caption: "Placeholder for TVL, revenue, and yield-distribution evidence once the chart export is ready.",
    visual: "reserve-flow",
  },
  { type: "heading", text: "5. Pendle Listing Value" },
  {
    type: "paragraph",
    text: "The first diligence step is to separate product-market fit from headline yield. A useful listing should improve price discovery, duration expression, and exit liquidity for allocators.",
  },
  {
    type: "checklist",
    title: "Early Listing Checklist",
    items: [
      { text: "Confirm the Pendle pool, maturity, and underlying yield source before treating quoted APY as investable.", level: "amber" },
      { text: "Track whether liquidity remains after launch incentives normalize.", level: "amber" },
      { text: "Compare implied yield with more established stablecoin yield venues.", level: "green" },
    ],
  },
  { type: "heading", text: "6. Risk Checklist" },
  {
    type: "checklist",
    title: "Risk Checklist",
    items: [
      { text: "Liquidity risk: Pendle depth may not match headline TVL during stress.", level: "amber" },
      { text: "Source risk: allocator yield quality depends on venue-level transparency.", level: "red" },
      { text: "Duration risk: fixed-yield buyers inherit exit risk before maturity.", level: "amber" },
      { text: "Incentive risk: launch rewards can mask organic demand.", level: "amber" },
      { text: "Stablecoin risk: USDD-specific peg and reserve assumptions need independent verification.", level: "red" },
    ],
  },
  { type: "heading", text: "7. My Take" },
  {
    type: "paragraph",
    text: "My base case is constructive but conditional. The Pendle listing is strategically useful if it turns USDD yield into a more transparent market signal. It is not enough by itself to underwrite the asset without allocator-level evidence.",
  },
  {
    type: "quote",
    text: "The question is not whether Pendle can make USDD yield tradable. The question is whether tradability improves underwriting quality.",
    attribution: "Yash Khandelwal",
  },
  {
    type: "sources",
    items: ["USDD documentation", "Pendle market pages", "Protocol reserve disclosures", "On-chain pool data"],
  },
];

export const articles: Article[] = [
  {
    slug: "usdd-pendle-investment-memo",
    title: "USDD Investment Memo: Why the Pendle Listing Matters",
    thesis: "Representative memo draft on USDD, Pendle, allocator yield, and fixed-yield market structure.",
    tags: ["USDD", "Pendle", "Stablecoins", "Yield"],
    date: "2025-01-20",
    readTime: 12,
    status: "Memo",
    category: "Stablecoin Yield",
    featured: true,
    conclusion: "The Pendle listing is useful only if it improves transparency around allocator yield and creates durable liquidity beyond launch incentives.",
    coverArt: { variant: "flows", colors: ["#0b2f1e", "#32d583", "#facc15"], label: "UP" },
    content: usddPendleContent,
  },
  {
    slug: "stablecoin-sandwich-dollar-journey",
    title: "The Stablecoin Sandwich: Anatomy of the Dollar's Journey",
    thesis: "Placeholder for a future memo on how stablecoin dollars move through issuers, venues, and yield wrappers.",
    tags: ["Stablecoins", "Yield", "Cash Flows"],
    date: "2025-01-10",
    readTime: 8,
    status: "Draft",
    category: "Stablecoin Yield",
    featured: true,
    content: placeholderContent("The Stablecoin Sandwich", "reserve-flow"),
  },
  {
    slug: "prediction-market-making-probability-space",
    title: "Market Making for Prediction Markets: A Probability-Space Approach",
    thesis: "Placeholder for a future research note on prediction-market liquidity and market-making frameworks.",
    tags: ["Prediction Markets", "Market Making", "Liquidity"],
    date: "2025-01-08",
    readTime: 7,
    status: "Researching",
    category: "Prediction Markets",
    content: placeholderContent("Market Making for Prediction Markets", "market-map"),
  },
  {
    slug: "consumer-crypto-finance-map",
    title: "Consumer Crypto Finance Map",
    thesis: "Placeholder map for consumer crypto finance products, rails, and unanswered research questions.",
    tags: ["Consumer Crypto", "Finance", "Market Map"],
    date: "2025-01-05",
    readTime: 6,
    status: "Map",
    category: "Consumer Crypto",
    content: placeholderContent("Consumer Crypto Finance Map", "market-map"),
  },
  {
    slug: "agent-payment-infrastructure-beyond-x402",
    title: "Agent Payment Infrastructure Beyond x402",
    thesis: "Placeholder for research on agent-payment infrastructure, payment flows, and open protocol questions.",
    tags: ["Agents", "Payments", "Infrastructure"],
    date: "2025-01-03",
    readTime: 6,
    status: "Researching",
    category: "Agent Infrastructure",
    featured: true,
    content: placeholderContent("Agent Payment Infrastructure", "agent-network"),
  },
  {
    slug: "protocol-revenue-incentive-durability",
    title: "Protocol Revenue vs Incentive Durability",
    thesis: "Placeholder memo for comparing protocol revenue, incentive design, and durability questions.",
    tags: ["Protocol Research", "Revenue", "Incentives"],
    date: "2024-12-20",
    readTime: 7,
    status: "Memo",
    category: "Protocol Research",
    content: placeholderContent("Protocol Revenue vs Incentive Durability", "rate-spread"),
  },
  {
    slug: "pendle-fixed-yield-markets",
    title: "Pendle Fixed-Yield Markets",
    thesis: "Placeholder for a future fixed-income research note connected to the USDD/Pendle memo.",
    tags: ["Pendle", "Fixed Yield", "DeFi"],
    date: "2024-12-12",
    readTime: 7,
    status: "Draft",
    category: "DeFi Fixed Income",
    content: placeholderContent("Pendle Fixed-Yield Markets", "rate-spread"),
  },
  {
    slug: "on-chain-market-structure-notes",
    title: "On-chain Market Structure Notes",
    thesis: "Placeholder notes for market-structure questions that need source-backed research before publication.",
    tags: ["Market Structure", "Liquidity", "Research Notes"],
    date: "2024-12-02",
    readTime: 5,
    status: "Researching",
    category: "Market Structure",
    content: placeholderContent("On-chain Market Structure Notes", "market-map"),
  },
];
