import type { Dashboard } from "../types/content";

export const dashboards: Dashboard[] = [
  {
    slug: "stablecoin-yield-monitor",
    title: "sUSDD Pendle Monitor",
    status: "Building",
    researchQuestion: "Which parts of the sUSDD/Pendle setup need monitoring before the dashboard becomes automated?",
    dataSources: ["Static/manual snapshot — not live data.", "USDD memo", "Pendle manual review", "DeFiLlama manual review"],
    tool: "Custom",
    relatedArticleSlug: "usdd-pendle-investment-memo",
    specSlug: "stablecoin-yield-susdd-pendle-monitor",
    preview: { variant: "flows", colors: ["#0f3b25", "#32d583", "#7dd3fc"], label: "SY" },
  },
  {
    slug: "pendle-fixed-yield-markets",
    title: "Pendle Fixed-Yield Markets",
    status: "Building",
    researchQuestion: "What evidence is needed to track fixed-yield markets connected to the Pendle research shelf?",
    dataSources: ["Source list to be added"],
    tool: "Dune",
    relatedArticleSlug: "usdd-pendle-investment-memo",
    preview: { variant: "grid", colors: ["#172554", "#60a5fa", "#34d399"], label: "FI" },
  },
  {
    slug: "protocol-revenue-vs-incentives",
    title: "Protocol Revenue vs Incentives",
    status: "Planned",
    researchQuestion: "What source-backed fields are needed to compare protocol revenue and incentive durability?",
    dataSources: ["Source list to be added"],
    tool: "Python",
    preview: { variant: "grid", colors: ["#422006", "#f59e0b", "#32d583"], label: "PR" },
  },
  {
    slug: "consumer-crypto-finance-map",
    title: "Consumer Crypto Finance Map",
    status: "Planned",
    researchQuestion: "What categories should structure a consumer crypto finance map before data collection starts?",
    dataSources: ["Source list to be added"],
    tool: "Observable",
    preview: { variant: "orbits", colors: ["#064e3b", "#34d399", "#facc15"], label: "CC" },
  },
  {
    slug: "agent-payment-infrastructure-map",
    title: "Agent Payment Infrastructure Map",
    status: "Planned",
    researchQuestion: "What open questions define the agent-payment infrastructure research shelf?",
    dataSources: ["Source list to be added"],
    tool: "Custom",
    preview: { variant: "nodes", colors: ["#1e1b4b", "#a78bfa", "#32d583"], label: "AI" },
  },
];
