import type { Dashboard } from "../types/content";

export const dashboards: Dashboard[] = [
  {
    slug: "stablecoin-yield-tracker",
    title: "Stablecoin Yield Tracker",
    status: "Building",
    researchQuestion: "Which stablecoin vaults are offering anomalous APYs versus the DSR benchmark?",
    dataSources: ["Defillama", "Aave", "Compound", "Sky"],
    tool: "Dune",
    relatedArticleSlug: "stablecoin-yield-mechanics",
    preview: { variant: "flows", colors: ["#0f3b25", "#32d583", "#7dd3fc"], label: "SY" },
  },
  {
    slug: "defi-rate-dashboard",
    title: "DeFi Rate Monitor",
    status: "Building",
    researchQuestion: "How do Aave, Compound, and Euler borrow rates compare to TradFi short-duration yields?",
    dataSources: ["Aave v3", "Compound v3", "Federal Reserve H.15"],
    tool: "Observable",
    relatedArticleSlug: "aave-rate-market",
    preview: { variant: "grid", colors: ["#172554", "#60a5fa", "#34d399"], label: "FI" },
  },
  {
    slug: "protocol-revenue",
    title: "Protocol Revenue League Table",
    status: "Building",
    researchQuestion: "Which protocols generated the most fee revenue in the last 90 days on a risk-adjusted basis?",
    dataSources: ["Token Terminal", "Defillama"],
    tool: "Python",
    relatedArticleSlug: "protocol-revenue-map",
    preview: { variant: "grid", colors: ["#422006", "#f59e0b", "#32d583"], label: "PR" },
  },
  {
    slug: "mev-flow-tracker",
    title: "MEV Flow Tracker",
    status: "Building",
    researchQuestion: "How much value is extracted per block by type: arbitrage, sandwich, and liquidation?",
    dataSources: ["Flashbots", "Eigenphi", "Dune"],
    tool: "Dune",
    relatedArticleSlug: "mev-anatomy",
    preview: { variant: "blocks", colors: ["#450a0a", "#fb7185", "#f59e0b"], label: "MEV" },
  },
  {
    slug: "agent-payment-map",
    title: "Agent Economy Monitor",
    status: "Planned",
    researchQuestion: "What APIs are being consumed by autonomous AI agents, and at what payment volumes?",
    dataSources: ["x402 registry", "On-chain logs"],
    tool: "Custom",
    relatedArticleSlug: "agent-payments-x402",
    preview: { variant: "nodes", colors: ["#1e1b4b", "#a78bfa", "#32d583"], label: "AP" },
  },
];
